version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: short-url-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - short-url-network

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short-url-service-1
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/short-url?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - SERVER_PORT=8080
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - INSTANCE_ID=1
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/app/gc.log
    networks:
      - short-url-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short-url-service-2
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/short-url?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - SERVER_PORT=8080
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - INSTANCE_ID=2
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/app/gc.log
    networks:
      - short-url-network

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short-url-service-3
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/short-url?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - SERVER_PORT=8080
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - INSTANCE_ID=3
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/app/gc.log
    networks:
      - short-url-network

  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: short-url-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=short-url
      - MYSQL_USER=short-url
      - MYSQL_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - short-url-network

  # Kafka服务
  kafka:
    image: bitnami/kafka:3.6
    container_name: short-url-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - short-url-network

  redis:
    image: redis:latest
    container_name: short-url-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - short-url-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
#    environment:
#      - STORAGE_TYPE=mysql
#      - MYSQL_HOST=jdbc:mysql://mysql:3306/short-url?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#      - MYSQL_TCP_PORT=3306
#      - MYSQL_DB=zipkin
#      - MYSQL_USER=root
#      - MYSQL_PASS=123456
#    depends_on:
#      - mysql
    networks:
      - short-url-network

volumes:
  mysql-data:
    driver: local
  kafka-data:
    driver: local
  redis_data:
    driver: local

networks:
  short-url-network:
    driver: bridge