version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short-url-service
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/short-url?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=true
      - SERVER_PORT=8080
    networks:
      - short-url-network

  db:
    image: mysql:8.0
    container_name: short-url-db
    restart: always
    environment:
      - MYSQL_DATABASE=short-url
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - short-url-network

volumes:
  mysql-data:

networks:
  short-url-network:
    driver: bridge