server:
  port: 8080
  tomcat:
    threads:
      max: 350
      min-spare: 30
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000

spring:
  application:
    name: short-url
  datasource:
    url: jdbc:mysql://localhost:3306/short-url?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.type.mapping: shortUrlMessage:com.example.shorturl.message.ShortUrlMessage
    consumer:
      group-id: short-url-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.type.mapping: shortUrlMessage:com.example.shorturl.message.ShortUrlMessage
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有端点
  endpoint:
    health:
      show-details: always  # 显示详细的健康检查信息
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
  server:
    port: 8081  # Actuator 端点端口


  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    root: INFO
    com.example.shorturl: DEBUG